### ISSUE TITLE
PHP Warning when version changes ...

### ISSUE THREAD

**Issue by lat9** [lat9/sitemapxml#17]
... if the upgrade happens when viewing (or coming from) the `sitemapxml` tool's page, since the language constants associated with the installation are included in the plugin's main language file:
```
[20-May-2023 12:16:49 UTC] Request URI: /mysite/myadmin/index.php?cmd=login&camefrom=sitemapxml.php, IP address: 127.0.0.1, Language id 1
#0 [internal function]: zen_debug_error_handler()
#1 C:\xampp\htdocs\mysite\myadmin\includes\languages\english\sitemapxml.php(33): define()
#2 C:\xampp\htdocs\mysite\myadmin\includes\modules\sitemapxml_install.php(13): require_once('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\mysite\myadmin\includes\init_includes\init_sitemapxml.php(96): require_once('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\mysite\includes\autoload_func.php(40): require_once('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\mysite\myadmin\includes\application_top.php(42): require('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\mysite\myadmin\login.php(8): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\mysite\myadmin\index.php(11): require('C:\\xampp\\htdocs...')
--> PHP Warning: Constant HEADING_TITLE already defined in C:\xampp\htdocs\mysite\myadmin\includes\languages\english\sitemapxml.php on line 33.
```

**Comment by lat9** [comment]
Need to split the language text associated with the configuration settings from those used by the admin tool.
