### ISSUE TITLE
Product-reviews/reviews/manufacturers sitemap throws deprecations if both added and last-modified dates are null

### ISSUE THREAD

**Issue by lat9** [lat9/sitemapxml#49]
... as identified in [this](https://www.zen-cart.com/showthread.php?126810-SitemapXML-v-2&p=1404284) Zen Cart support-thread posting.
```
[22-Nov-2024 16:21:15 America/Los_Angeles] Request URI: /index.php?main_page=sitemapxml&rebuild=yes, IP address: 98.45.172.132, Language id 1
#0 [internal function]: zen_debug_error_handler()
#1 /includes/classes/sitemapxml.php(225): strtotime()
#2 /includes/modules/pages/sitemapxml/sitemapxml_products_reviews.php(37): zen_SiteMapXML->writeItem()
#3 /includes/templates/template_default/sitemapxml/tpl_main_page.php(21): require('/home/zch1akhw6...')
#4 /index.php(95): require('/home/zch1akhw6...')
--> PHP Deprecated: strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated in /includes/classes/sitemapxml.php on line 225.
```

**Comment by lat9** [comment]
`sitemap_reviews.php` is also affected:
```
[29-Nov-2024 18:51:29 America/Los_Angeles] Request URI: /index.php?main_page=sitemapxml&rebuild=yes, IP address: 24.4.88.128, Language id 1
#0 [internal function]: zen_debug_error_handler()
#1 /includes/classes/sitemapxml.php(225): strtotime()
#2 /includes/modules/pages/sitemapxml/sitemapxml_reviews.php(32): zen_SiteMapXML->writeItem()
#3 /includes/templates/template_default/sitemapxml/tpl_main_page.php(21): require('/home/zch1akhw6...')
#4 /index.php(95): require('/home/zch1akhw6...')
--> PHP Deprecated: strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated in /includes/classes/sitemapxml.php on line 225.
```
